### ISSUE TITLE
Install issue?

### ISSUE THREAD

**Issue by LanHikariDS** [RockmanEXEZone/chaudloader#11]
Trying to install chaudloader just causes the window to flash and do nothing. Opening the program through a prior command prompt window shows
`Welcome to the chaudloader installer.

thread 'main' panicked at 'range end index 20 out of range for slice of length 0', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\library\alloc\src\vec\mod.rs:1992:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by LanHikariDS** [comment]
I have no idea how to do that, I tried "install.exe -RUST_BACKTRACE=1", and that threw an error

**Comment by LanHikariDS** [comment]
thread 'main' panicked at 'range end index 20 out of range for slice of length 0', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\library\alloc\src\vec\mod.rs:1992:36
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Setting backtrace to full shows-
thread 'main' panicked at 'range end index 20 out of range for slice of length 0', /rustc/2f2c438dce75d8cc532c3baa849eeddc0901802c\library\alloc\src\vec\mod.rs:1992:36
stack backtrace:
   0:     0x7ff628f53f4c - <unknown>
   1:     0x7ff628f67fab - <unknown>
   2:     0x7ff628f50209 - <unknown>
   3:     0x7ff628f53cfb - <unknown>
   4:     0x7ff628f55d49 - <unknown>
   5:     0x7ff628f559ff - <unknown>
   6:     0x7ff628f56236 - <unknown>
   7:     0x7ff628f5612d - <unknown>
   8:     0x7ff628f548c9 - <unknown>
   9:     0x7ff628f55e40 - <unknown>
  10:     0x7ff628f6fcd5 - <unknown>
  11:     0x7ff628f70204 - <unknown>
  12:     0x7ff628ee2492 - <unknown>
  13:     0x7ff628ee1f52 - <unknown>
  14:     0x7ff628ee06ff - <unknown>
  15:     0x7ff628ee079b - <unknown>
  16:     0x7ff628ee079b - <unknown>
  17:     0x7ff628ee1801 - <unknown>
  18:     0x7ff628ee3339 - <unknown>
  19:     0x7ff628edff65 - <unknown>
  20:     0x7ff628edcb50 - <unknown>
  21:     0x7ff628edb006 - <unknown>
  22:     0x7ff628ed424a - <unknown>
  23:     0x7ff628f48868 - <unknown>
  24:     0x7ff628edf85c - <unknown>
  25:     0x7ff628f6c7c4 - <unknown>
  26:     0x7ffbe13d7614 - BaseThreadInitThunk
  27:     0x7ffbe32826a1 - RtlUserThreadStart

**Comment by LanHikariDS** [comment]
Now BNLC doesn't open, and the modloader installer does the same thing as before

**Comment by LanHikariDS** [comment]
Yep. Preordered the collections through Steam, and have nearly 91 hours clocked in it.

**Comment by LanHikariDS** [comment]
I had a friend send me all his dlls (the two above, as well as chaudloader.toml and llua54.dll), and now the modloader opens for me when starting
